services:
  app:
    image: python:3.14-slim
    container_name: secure_user_app
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      ADMIN_USER: "admin"
      ADMIN_PASS: "admin123"
    command: python /app/main.py
